### ISSUE TITLE
Documentation python code

### ISSUE THREAD

**Issue by asljhdgf** [ES-EDU-SIEGMA/User-Interface#20]
## Description
At the moment there is no current documentation of the python code. To make it easier to work with the code in the future add some simple documentation.

## ToDo
- [x] check comments in python code
- [x] add simple graphics
- [x] write documentation text
