### ISSUE TITLE
Fix main branch

### ISSUE THREAD

**Issue by DavidFederl** [ES-EDU-SIEGMA/User-Interface#4]
## Description

Due to fact that the current code in the branch can't be executed this should be fixed.

## ToDo

- [x] Merge `gui/src` with `refactor_gui`
- [x] Merge `refactor_gui` into `main`
- [x] Fix `main` to allow the application to run on dev machines the RPI with JSON as data source

---

Estimated Time: 8h
