### ISSUE TITLE
Replaced & Test the Touchscreen

### ISSUE THREAD

**Issue by DavidFederl** [ES-EDU-SIEGMA/User-Interface#7]
## Description

Install the newly delivered parts into the machine and connect all components to the PI

## Related User Stories

- [Cleaning](https://github.com/orgs/ES-EDU-SIEGMA/projects/1/views/1?pane=issue&itemId=29365987)
- [60 Seconds to drink](https://github.com/orgs/ES-EDU-SIEGMA/projects/1/views/1?pane=issue&itemId=29367077)
- [Improve UI](https://github.com/orgs/ES-EDU-SIEGMA/projects/1/views/1?pane=issue&itemId=29367221)

## ToDo

- [x] Integrate new Touchscreen with Raspberry Pi
- [x] Add USB-Hub for improved Cable Manegament
- [x] Add Cable to connect display-controller to the Transformer
